name: task_manager
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.2
  nb_utils: ^7.0.7
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  collection: ^1.18.0
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
